### ISSUE TITLE
A question about one displayed GIF

### ISSUE THREAD

**Issue by LPHFAQ** [changhaonan/STAR-no-prior#1]
Hello, this work is very excellent but there's a problem with one displayed GIF (**the 6th of "More results on challenging scenes"**), when fetching the third item on the desk, the first item ( seems like a can) changes into **the same color as the table** (both green), does the system incorrectly regard the first item as the same topology as the table? Or it's the problem that the number of color used for display is not enough?
![Snipaste_2023-09-09_10-46-51](https://github.com/changhaonan/STAR-no-prior/assets/57347617/fd8a0746-df4e-442e-8df4-bd798ac38363)

**Comment by changhaonan** [comment]
Thanks for your feedback. This is actually two types of green... I didn't select the color very well.

**Comment by LPHFAQ** [comment]
你好，你发送的邮件我已受到，我会尽快回复。
