### ISSUE TITLE
Request for source code

### ISSUE THREAD

**Issue by nirmalsnair** [changhaonan/STAR-no-prior#2]
I've been exploring this project and found it immensely beneficial for a project that I'm working on. However, I couldn't locate the source code in the repository. Is there any plan to upload the source code in the near future?

**Comment by changhaonan** [comment]
Actually I can send you the source code through e-mail If you want to use it to learn the code. As for deployment, I am currently busy on other staff. So I don't have time clear the code for deployment.

**Comment by nirmalsnair** [comment]
Thanks, could you please send the source code and related files to _nirmal (dot) nair (at) outlook (dot) com_?

**Comment by nirmalsnair** [comment]
@changhaonan Hi, have you had a chance to send the code via email? You can reach me at _nirmal.nair@outlook.com_. Thanks!

**Comment by changhaonan** [comment]
Check the email. I have sent you.
